### ISSUE TITLE
PROTIP: Add __init__.py to tests directory to make it a module

### ISSUE THREAD

**Issue by hancush** [datamade/testing-guidelines#14]
I've certainly spent, idk, 10 minutes of my life wondering why my tests don't run when I forget this. Let's add a tip to the test setup guide.

**Comment by reginafcompton** [comment]
yes - I spend 15 minutes of my life yesterday wondering this exact thing.

**Comment by hancush** [comment]
@reginafcompton It was a good reminder! ;-)
